/* This file is auto-generated by gen_status_update_code.py script, manual changes will be lost */

#include "nanopb/pb_decode.h"
#include "nanopb/pb_encode.h"
#include "MessageDefinitions.pb.h"
#include "globalState.h"
#include "buildStatusUpdate.h"

void buildStatusUpdate(StatusUpdate * status) {
	status->has_timestamp = true;
	status->timestamp = Get_timestamp();
	status->has_voltageLV = true;
	status->voltageLV = Get_voltageLV();
	status->has_voltageHV = true;
	status->voltageHV = Get_voltageHV();
	status->has_locLongitude = true;
	status->locLongitude = Get_locLongitude();
	status->has_locLatitude = true;
	status->locLatitude = Get_locLatitude();
	status->has_locAltitude = true;
	status->locAltitude = Get_locAltitude();
	status->has_speedGPS = true;
	status->speedGPS = Get_speedGPS();
	status->has_speedInverter = true;
	status->speedInverter = Get_speedInverter();
	status->has_speedWheelSensor = true;
	status->speedWheelSensor = Get_speedWheelSensor();
	status->has_speedDisplayed = true;
	status->speedDisplayed = Get_speedDisplayed();
	status->has_minInverterCurr = true;
	status->minInverterCurr = Get_minInverterCurr();
	status->has_maxInverterCurr = true;
	status->maxInverterCurr = Get_maxInverterCurr();
	status->has_avgInverterCurr = true;
	status->avgInverterCurr = Get_avgInverterCurr();
	status->has_tempInverter = true;
	status->tempInverter = Get_tempInverter();
	status->has_tempMotor = true;
	status->tempMotor = Get_tempMotor();
	status->has_minChargerCurrent = true;
	status->minChargerCurrent = Get_minChargerCurrent();
	status->has_maxChargerCurrent = true;
	status->maxChargerCurrent = Get_maxChargerCurrent();
	status->has_avgChargerCurrent = true;
	status->avgChargerCurrent = Get_avgChargerCurrent();
	status->has_tempCharger = true;
	status->tempCharger = Get_tempCharger();
	status->has_tempDCDC = true;
	status->tempDCDC = Get_tempDCDC();
	status->has_fanDCDCState = true;
	status->fanDCDCState = Get_fanDCDCState();
	status->has_frontLong = true;
	status->frontLong = Get_frontLong();
	status->has_frontShort = true;
	status->frontShort = Get_frontShort();
	status->has_DRL = true;
	status->DRL = Get_DRL();
	status->has_frontFog = true;
	status->frontFog = Get_frontFog();
	status->has_backFog = true;
	status->backFog = Get_backFog();
	status->has_breakLight = true;
	status->breakLight = Get_breakLight();
	status->has_hazardButton = true;
	status->hazardButton = Get_hazardButton();
	status->has_panicButton = true;
	status->panicButton = Get_panicButton();
	status->has_seatHeaterFR = true;
	status->seatHeaterFR = Get_seatHeaterFR();
	status->has_seatHeaterFL = true;
	status->seatHeaterFL = Get_seatHeaterFL();
	status->has_seatHeaterRR = true;
	status->seatHeaterRR = Get_seatHeaterRR();
	status->has_seatHeaterRL = true;
	status->seatHeaterRL = Get_seatHeaterRL();
	status->has_seatSensorFR = true;
	status->seatSensorFR = Get_seatSensorFR();
	status->has_seatSensorFL = true;
	status->seatSensorFL = Get_seatSensorFL();
	status->has_seatSensorRR = true;
	status->seatSensorRR = Get_seatSensorRR();
	status->has_seatSensorRL = true;
	status->seatSensorRL = Get_seatSensorRL();
	status->has_blinkerLeft = true;
	status->blinkerLeft = Get_blinkerLeft();
	status->has_blinkerRight = true;
	status->blinkerRight = Get_blinkerRight();
	status->has_doorOpenFR = true;
	status->doorOpenFR = Get_doorOpenFR();
	status->has_doorOpenFL = true;
	status->doorOpenFL = Get_doorOpenFL();
	status->has_doorOpenRR = true;
	status->doorOpenRR = Get_doorOpenRR();
	status->has_doorOpenRL = true;
	status->doorOpenRL = Get_doorOpenRL();
	status->has_doorLockedFR = true;
	status->doorLockedFR = Get_doorLockedFR();
	status->has_doorLockedFL = true;
	status->doorLockedFL = Get_doorLockedFL();
	status->has_doorLockedRR = true;
	status->doorLockedRR = Get_doorLockedRR();
	status->has_doorLockedRL = true;
	status->doorLockedRL = Get_doorLockedRL();

	/* activeError not included because repeated fields need special handling */
}

