/* This file is auto-generated by gen_status_update_code.py script, manual changes will be lost */

#include "nanopb/pb_decode.h"
#include "nanopb/pb_encode.h"
#include "MessageDefinitions.pb.h"
#include "globalState.h"
#include "buildStatusUpdate.h"

void buildStatusUpdate(StatusUpdate * status) {
	status->has_timestamp = true;
	status->timestamp = Get_timestamp();
	status->has_locLongitude = true;
	status->locLongitude = Get_locLongitude();
	status->has_locLatitude = true;
	status->locLatitude = Get_locLatitude();
	status->has_locAltitude = true;
	status->locAltitude = Get_locAltitude();
	status->has_speedGPS = true;
	status->speedGPS = Get_speedGPS();
	status->has_seatOccupiedFR = true;
	status->seatOccupiedFR = Get_seatOccupiedFR();
	status->has_seatOccupiedFL = true;
	status->seatOccupiedFL = Get_seatOccupiedFL();
	status->has_seatOccupiedRR = true;
	status->seatOccupiedRR = Get_seatOccupiedRR();
	status->has_seatOccupiedRL = true;
	status->seatOccupiedRL = Get_seatOccupiedRL();
	status->has_blinkerLeft = true;
	status->blinkerLeft = Get_blinkerLeft();
	status->has_blinkerRight = true;
	status->blinkerRight = Get_blinkerRight();
	status->has_doorOpenFR = true;
	status->doorOpenFR = Get_doorOpenFR();
	status->has_doorOpenFL = true;
	status->doorOpenFL = Get_doorOpenFL();
	status->has_doorOpenRR = true;
	status->doorOpenRR = Get_doorOpenRR();
	status->has_doorOpenRL = true;
	status->doorOpenRL = Get_doorOpenRL();
	status->has_vehicleLocked = true;
	status->vehicleLocked = Get_vehicleLocked();


}

