/* This file is auto-generated by gen_global_state_code.py script, manual changes will be lost */
#ifndef RELAXED_STATUSUPDATECONFIG_H_
#define RELAXED_STATUSUPDATECONFIG_H_

#define STATUS_UPDATE                  \
	X(int32_t   , timestamp           , 0) \
	X(float     , locLongitude        , 0) \
	X(float     , locLatitude         , 0) \
	X(float     , locAltitude         , 0) \
	X(float     , speedGPS            , 0) \
	X(bool      , seatOccupiedFR      , 0) \
	X(bool      , seatOccupiedFL      , 0) \
	X(bool      , seatOccupiedRR      , 0) \
	X(bool      , seatOccupiedRL      , 0) \
	X(bool      , blinkerLeft         , 0) \
	X(bool      , blinkerRight        , 0) \
	X(bool      , doorOpenFR          , 0) \
	X(bool      , doorOpenFL          , 0) \
	X(bool      , doorOpenRR          , 0) \
	X(bool      , doorOpenRL          , 0) \
	X(bool      , vehicleLocked       , 0) \



#endif /* RELAXED_STATUSUPDATECONFIG_H_*/

