/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Mon Aug 22 13:54:52 2016. */

#include "CCU_internal.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const CUcmd_SetWindowPosition_WINDOW CUcmd_SetWindowPosition_window_default = CUcmd_SetWindowPosition_WINDOW_FRONT_RIGHT;
const CUcmd_SetLightState_LIGHT CUcmd_SetLightState_light_default = CUcmd_SetLightState_LIGHT_DRL;
const CUcmd_SetPRNDstate_PRND CUcmd_SetPRNDstate_state_default = CUcmd_SetPRNDstate_PRND_NEUTRAL;
const SpiriStatus_activeError_SPIRIERRORS SpiriStatus_activeError_activeError_default = SpiriStatus_activeError_SPIRIERRORS_ERR_NO_ERROR;


const pb_field_t CUcmd_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, CUcmd, timestamp, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_NoCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetWindowPosition_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CUcmd_SetWindowPosition, window, window, &CUcmd_SetWindowPosition_window_default),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, CUcmd_SetWindowPosition, position_perc, window, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetWindowWasherState_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, CUcmd_SetWindowWasherState, state, state, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetSeatHeaterState_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, CUcmd_SetSeatHeaterState, state, state, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetLightState_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CUcmd_SetLightState, light, light, &CUcmd_SetLightState_light_default),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, CUcmd_SetLightState, state, light, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetPRNDstate_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CUcmd_SetPRNDstate, state, state, &CUcmd_SetPRNDstate_state_default),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetChargingState_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, CUcmd_SetChargingState, state, state, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetChargingProperties_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, CUcmd_SetChargingProperties, charging_upper_limit_perc, charging_upper_limit_perc, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetInverterProperties_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, CUcmd_SetInverterProperties, maximal_torque, maximal_torque, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetHornState_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, CUcmd_SetHornState, state, state, 0),
    PB_LAST_FIELD
};

const pb_field_t CUcmd_SetMoodLightState_fields[5] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, CUcmd_SetMoodLightState, intensity, intensity, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, CUcmd_SetMoodLightState, colorR, intensity, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, CUcmd_SetMoodLightState, colorG, colorR, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, CUcmd_SetMoodLightState, colorB, colorG, 0),
    PB_LAST_FIELD
};

const pb_field_t SpiriStatus_fields[49] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, SpiriStatus, voltageLV, voltageLV, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, voltageHV, voltageLV, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, locLongitude, voltageHV, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, locLatitude, locLongitude, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, locAltitude, locLatitude, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, speedGPS, locAltitude, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, speedInverter, speedGPS, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, speedWheelSensor, speedInverter, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, speedDisplayed, speedWheelSensor, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, minInverterCurr, speedDisplayed, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, maxInverterCurr, minInverterCurr, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, avgInverterCurr, maxInverterCurr, 0),
    PB_FIELD( 13, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, tempInverter, avgInverterCurr, 0),
    PB_FIELD( 14, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, tempMotor, tempInverter, 0),
    PB_FIELD( 15, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, minChargerCurrent, tempMotor, 0),
    PB_FIELD( 16, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, maxChargerCurrent, minChargerCurrent, 0),
    PB_FIELD( 17, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, avgChargerCurrent, maxChargerCurrent, 0),
    PB_FIELD( 18, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, tempCharger, avgChargerCurrent, 0),
    PB_FIELD( 19, FLOAT   , OPTIONAL, STATIC  , OTHER, SpiriStatus, tempDCDC, tempCharger, 0),
    PB_FIELD( 20, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, fanDCDCState, tempDCDC, 0),
    PB_FIELD( 21, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, frontLong, fanDCDCState, 0),
    PB_FIELD( 22, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, frontShort, frontLong, 0),
    PB_FIELD( 23, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, DRL, frontShort, 0),
    PB_FIELD( 24, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, frontFog, DRL, 0),
    PB_FIELD( 25, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, backFog, frontFog, 0),
    PB_FIELD( 26, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, breakLight, backFog, 0),
    PB_FIELD( 28, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, hazardButton, breakLight, 0),
    PB_FIELD( 29, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, panicButton, hazardButton, 0),
    PB_FIELD( 30, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatHeaterFR, panicButton, 0),
    PB_FIELD( 31, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatHeaterFL, seatHeaterFR, 0),
    PB_FIELD( 32, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatHeaterRR, seatHeaterFL, 0),
    PB_FIELD( 33, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatHeaterRL, seatHeaterRR, 0),
    PB_FIELD( 34, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatSensorFR, seatHeaterRL, 0),
    PB_FIELD( 35, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatSensorFL, seatSensorFR, 0),
    PB_FIELD( 36, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatSensorRR, seatSensorFL, 0),
    PB_FIELD( 37, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, seatSensorRL, seatSensorRR, 0),
    PB_FIELD( 38, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, blinkerLeft, seatSensorRL, 0),
    PB_FIELD( 39, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, blinkerRight, blinkerLeft, 0),
    PB_FIELD( 40, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorOpenFR, blinkerRight, 0),
    PB_FIELD( 41, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorOpenFL, doorOpenFR, 0),
    PB_FIELD( 42, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorOpenRR, doorOpenFL, 0),
    PB_FIELD( 43, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorOpenRL, doorOpenRR, 0),
    PB_FIELD( 44, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorLockedFR, doorOpenRL, 0),
    PB_FIELD( 45, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorLockedFL, doorLockedFR, 0),
    PB_FIELD( 46, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorLockedRR, doorLockedFL, 0),
    PB_FIELD( 47, BOOL    , OPTIONAL, STATIC  , OTHER, SpiriStatus, doorLockedRL, doorLockedRR, 0),
    PB_FIELD( 48, MESSAGE , REPEATED, CALLBACK, OTHER, SpiriStatus, error, doorLockedRL, &SpiriStatus_activeError_fields),
    PB_FIELD(100, INT32   , REQUIRED, STATIC  , OTHER, SpiriStatus, timestamp, error, 0),
    PB_LAST_FIELD
};

const pb_field_t SpiriStatus_activeError_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, SpiriStatus_activeError, activeError, activeError, &SpiriStatus_activeError_activeError_default),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Event, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Event, level, timestamp, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Event, aditional_info, level, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, Event, event, aditional_info, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SpiriStatus, error) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_CUcmd_CUcmd_NoCommand_CUcmd_SetWindowPosition_CUcmd_SetWindowWasherState_CUcmd_SetSeatHeaterState_CUcmd_SetLightState_CUcmd_SetPRNDstate_CUcmd_SetChargingState_CUcmd_SetChargingProperties_CUcmd_SetInverterProperties_CUcmd_SetHornState_CUcmd_SetMoodLightState_SpiriStatus_SpiriStatus_activeError_Event)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SpiriStatus, error) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_CUcmd_CUcmd_NoCommand_CUcmd_SetWindowPosition_CUcmd_SetWindowWasherState_CUcmd_SetSeatHeaterState_CUcmd_SetLightState_CUcmd_SetPRNDstate_CUcmd_SetChargingState_CUcmd_SetChargingProperties_CUcmd_SetInverterProperties_CUcmd_SetHornState_CUcmd_SetMoodLightState_SpiriStatus_SpiriStatus_activeError_Event)
#endif


/* @@protoc_insertion_point(eof) */
