/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Thu Nov 24 11:35:32 2016. */

#include "MessageDefinitions.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ContainerMessage_fields[4] = {
    PB_ONEOF_FIELD(message,   1, MESSAGE , ONEOF, STATIC  , FIRST, ContainerMessage, status, status, &StatusUpdate_fields),
    PB_ONEOF_FIELD(message,   2, MESSAGE , ONEOF, STATIC  , FIRST, ContainerMessage, commandRequest, commandRequest, &CommandRequest_fields),
    PB_ONEOF_FIELD(message,   3, MESSAGE , ONEOF, STATIC  , FIRST, ContainerMessage, commandResponse, commandResponse, &CommandResponse_fields),
    PB_LAST_FIELD
};

const pb_field_t StatusUpdate_fields[49] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, StatusUpdate, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, voltageLV, timestamp, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, voltageHV, voltageLV, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, locLongitude, voltageHV, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, locLatitude, locLongitude, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, locAltitude, locLatitude, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, speedGPS, locAltitude, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, speedInverter, speedGPS, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, speedWheelSensor, speedInverter, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, speedDisplayed, speedWheelSensor, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, minInverterCurr, speedDisplayed, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, maxInverterCurr, minInverterCurr, 0),
    PB_FIELD( 13, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, avgInverterCurr, maxInverterCurr, 0),
    PB_FIELD( 14, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, tempInverter, avgInverterCurr, 0),
    PB_FIELD( 15, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, tempMotor, tempInverter, 0),
    PB_FIELD( 16, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, minChargerCurrent, tempMotor, 0),
    PB_FIELD( 17, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, maxChargerCurrent, minChargerCurrent, 0),
    PB_FIELD( 18, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, avgChargerCurrent, maxChargerCurrent, 0),
    PB_FIELD( 19, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, tempCharger, avgChargerCurrent, 0),
    PB_FIELD( 20, FLOAT   , OPTIONAL, STATIC  , OTHER, StatusUpdate, tempDCDC, tempCharger, 0),
    PB_FIELD( 21, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, fanDCDCState, tempDCDC, 0),
    PB_FIELD( 22, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, frontLong, fanDCDCState, 0),
    PB_FIELD( 23, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, frontShort, frontLong, 0),
    PB_FIELD( 24, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, DRL, frontShort, 0),
    PB_FIELD( 25, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, frontFog, DRL, 0),
    PB_FIELD( 26, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, backFog, frontFog, 0),
    PB_FIELD( 27, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, breakLight, backFog, 0),
    PB_FIELD( 29, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, hazardButton, breakLight, 0),
    PB_FIELD( 30, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, panicButton, hazardButton, 0),
    PB_FIELD( 31, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatHeaterFR, panicButton, 0),
    PB_FIELD( 32, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatHeaterFL, seatHeaterFR, 0),
    PB_FIELD( 33, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatHeaterRR, seatHeaterFL, 0),
    PB_FIELD( 34, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatHeaterRL, seatHeaterRR, 0),
    PB_FIELD( 35, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatSensorFR, seatHeaterRL, 0),
    PB_FIELD( 36, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatSensorFL, seatSensorFR, 0),
    PB_FIELD( 37, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatSensorRR, seatSensorFL, 0),
    PB_FIELD( 38, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, seatSensorRL, seatSensorRR, 0),
    PB_FIELD( 39, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, blinkerLeft, seatSensorRL, 0),
    PB_FIELD( 40, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, blinkerRight, blinkerLeft, 0),
    PB_FIELD( 41, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorOpenFR, blinkerRight, 0),
    PB_FIELD( 42, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorOpenFL, doorOpenFR, 0),
    PB_FIELD( 43, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorOpenRR, doorOpenFL, 0),
    PB_FIELD( 44, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorOpenRL, doorOpenRR, 0),
    PB_FIELD( 45, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorLockedFR, doorOpenRL, 0),
    PB_FIELD( 46, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorLockedFL, doorLockedFR, 0),
    PB_FIELD( 47, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorLockedRR, doorLockedFL, 0),
    PB_FIELD( 48, BOOL    , OPTIONAL, STATIC  , OTHER, StatusUpdate, doorLockedRL, doorLockedRR, 0),
    PB_FIELD( 49, UENUM   , REPEATED, CALLBACK, OTHER, StatusUpdate, activeError, doorLockedRL, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandRequest_fields[6] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, CommandRequest, timestamp, timestamp, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, CommandRequest, commandOrigin, timestamp, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, CommandRequest, counter, commandOrigin, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, CommandRequest, type, counter, 0),
    PB_ONEOF_FIELD(argument,   5, MESSAGE , ONEOF, STATIC  , OTHER, CommandRequest, setDoorLock, type, &CommandRequest_SetDoorLock_fields),
    PB_LAST_FIELD
};

const pb_field_t CommandRequest_SetDoorLock_fields[2] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, CommandRequest_SetDoorLock, locked, locked, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandResponse_fields[7] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, CommandResponse, timestamp, timestamp, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, CommandResponse, commandOrigin, timestamp, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, CommandResponse, counter, commandOrigin, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, CommandResponse, result, counter, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, CommandResponse, error_message, result, 0),
    PB_ONEOF_FIELD(retval,   6, MESSAGE , ONEOF, STATIC  , OTHER, CommandResponse, softwareFileVersion, error_message, &CommandResponse_SoftwareFileVersion_fields),
    PB_LAST_FIELD
};

const pb_field_t CommandResponse_SoftwareFileVersion_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, CommandResponse_SoftwareFileVersion, minor, minor, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, CommandResponse_SoftwareFileVersion, major, minor, 0),
    PB_LAST_FIELD
};

typedef struct {
    FieldEndPoint source;
} source_struct;

static const pb_field_t source_field = 
      PB_FIELD(50000, ENUM    , OPTEXT, STATIC  , FIRST, source_struct, source, source, 0);

const pb_extension_type_t source = {
    NULL,
    NULL,
    &source_field
};

typedef struct {
    FieldEndPoint sink;
} sink_struct;

static const pb_field_t sink_field = 
      PB_FIELD(50001, ENUM    , OPTEXT, STATIC  , FIRST, sink_struct, sink, sink, 0);

const pb_extension_type_t sink = {
    NULL,
    NULL,
    &sink_field
};

typedef struct {
    uint32_t FileVersionMajor;
} FileVersionMajor_struct;

static const pb_field_t FileVersionMajor_field = 
      PB_FIELD(50010, UINT32  , OPTEXT, STATIC  , FIRST, FileVersionMajor_struct, FileVersionMajor, FileVersionMajor, 0);

const pb_extension_type_t FileVersionMajor = {
    NULL,
    NULL,
    &FileVersionMajor_field
};

typedef struct {
    uint32_t FileVersionMinor;
} FileVersionMinor_struct;

static const pb_field_t FileVersionMinor_field = 
      PB_FIELD(50011, UINT32  , OPTEXT, STATIC  , FIRST, FileVersionMinor_struct, FileVersionMinor, FileVersionMinor, 0);

const pb_extension_type_t FileVersionMinor = {
    NULL,
    NULL,
    &FileVersionMinor_field
};







/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ContainerMessage, message.status) < 65536 && pb_membersize(ContainerMessage, message.commandRequest) < 65536 && pb_membersize(ContainerMessage, message.commandResponse) < 65536 && pb_membersize(CommandRequest, argument.setDoorLock) < 65536 && pb_membersize(CommandResponse, retval.softwareFileVersion) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ContainerMessage_StatusUpdate_CommandRequest_CommandRequest_SetDoorLock_CommandResponse_CommandResponse_SoftwareFileVersion)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ContainerMessage, message.status) < 256 && pb_membersize(ContainerMessage, message.commandRequest) < 256 && pb_membersize(ContainerMessage, message.commandResponse) < 256 && pb_membersize(CommandRequest, argument.setDoorLock) < 256 && pb_membersize(CommandResponse, retval.softwareFileVersion) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ContainerMessage_StatusUpdate_CommandRequest_CommandRequest_SetDoorLock_CommandResponse_CommandResponse_SoftwareFileVersion)
#endif


/* @@protoc_insertion_point(eof) */
