/* This file is auto-generated by gen_global_state_code.py script, manual changes will be lost */
#ifndef RELAXED_COMMANDEXECUTION_H_
#define RELAXED_COMMANDEXECUTION_H_

#include "MessageDefinitions.pb.h"

#define COMMAND_EXECUTION_TYPES                  \
	X(SETDOORLOCK         ) \
	X(COMFORT             ) \
	X(LIGHTS              ) \
	X(DRIVETRAIN          ) \
	X(AP102CTRL           ) \

// function definitions
#define X(commandType)   void commandExecution_##commandType(const CommandRequest * request);
  COMMAND_EXECUTION_TYPES
#undef X

typedef enum {
	SUCCESS,
	UNAUTHORIZED,
	UNSUPPORTED,
	TIMEOUT,
	BLOCKED,
} commandResponse_t;

#endif /* RELAXED_COMMANDEXECUTION_H_*/

